services:
  open-tcg-postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: opentcg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  open-tcg-redis:
    image: redis:7
    container_name: opentcg-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres-data:
  redis-data:
