services:
  open-tcg-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_PORT: 5000
      DEV_SHOW_API_DOCS: TRUE
      DEV_SHOW_POSTGRES_LOGS: FALSE
      NODE_ENV: development
      TERMINUS_GRACEFUL_SHUTDOWN_DELAY_SECONDS: 10
      TERMINUS_HEALTHCHECK_HTTP_CHECK_URI: https://docs.nestjs.com
      TERMINUS_HEALTHCHECK_HEAP_THRESHOLD_MB: 50 
      TERMINUS_HEALTHCHECK_RSS_THRESHOLD_MB: 100
      TERMINUS_HEALTHCHECK_STORAGE_PATH: 'c:\'
      TERMINUS_HEALTHCHECK_STORAGE_THRESHOLD: 0.5
    ports:
      - "5000:5000"
    depends_on:
      - open-tcg-postgres
      - open-tcg-redis

